#!/bin/bash

source /init/init-common

cd /

copy_etc_2_docker_etc
copy_zimbra_common_etc_conf_2_docker_etc

tar cfz /docker_etc/logger.tar.gz /opt/zimbra/logger/
tar cfz /docker_etc/zimbra_ssh.tar.gz /opt/zimbra/.ssh
tar cfz /docker_etc/zimbra_saveconfig.tar.gz /opt/zimbra/.saveconfig
tar cfz /docker_etc/spamassassin.tar.gz /opt/zimbra/data/spamassassin/
tar cfz /docker_etc/etc_ssh.tar.gz /etc/ssh

tar cfz /docker_etc/jetty_base.tar.gz /opt/zimbra/jetty_base/
tar cfz /docker_etc/cache_debconf.tar.gz /var/cache/debconf