#!/bin/bash
source /init/init-common

#echo "/opt/zimbra/conf_0 - conf volume"
#rm -rf /opt/zimbra/conf/*

fix_zimbra_priviledges



#mv /opt/zimbra/conf_0/* /opt/zimbra/conf/

# NOTE: Currently genesis tests assume that the zmhostname == zimbra_default_domain
#       A fix for this is in progress
zimbra_fqdn=${ZIMBRA_HOST_NAME}
update_host_entry ${zimbra_fqdn}
update_tzdata_config
update_zmsetup_config_file

# Configure Zimbra
/opt/zimbra/libexec/zmsetup.pl -c /init/config
echo "Enable admin access via proxy. Required for SOAP Harness tests "
sudo -i -u zimbra /opt/zimbra/libexec/zmproxyconfig -e -w -C -H ${ZIMBRA_HOST_NAME}
echo "Disable max imap/pop3 max error limits. Required for Genesis"
sudo -i -u zimbra zmlocalconfig -e imap_max_consecutive_error=0 pop3_max_consecutive_error=0
post_zmsetup_configuration 
configure_staf 

echo '/etc -> /docker_etc/etc'
mkdir -p /docker_etc/etc
cp -av /etc/aliases.lmdb /etc/localtime /etc/timezone /docker_etc/etc
mkdir /docker_etc/etc/logrotate.d
cp -av /etc/logrotate.d/zimbra  /docker_etc/etc/logrotate.d/
mkdir /docker_etc/etc/rsyslog.d
cp -av /etc/rsyslog.d/50-default.conf /etc/rsyslog.d/60-zimbra.conf /docker_etc/etc/rsyslog.d

echo '/opt/zimbra/conf -> /docker_etc/conf'
mkdir -p /docker_etc/conf
cp -av /opt/zimbra/conf/* /docker_etc/conf/

echo '/opt/zimbra/common/conf,etc -> /docker_etc/common_conf, common_etc'
mkdir -p /docker_etc/common_conf 
mkdir -p /docker_etc/common_etc
cp -av /opt/zimbra/common/conf/* /docker_etc/common_conf/
cp -av /opt/zimbra/common/etc/* /docker_etc/common_etc/


echo "SETUP COMPLETE"
/bin/sleep infinity

