#!/bin/bash

# hernad 31.10.2018; v30

source /init/init-common

if  [ -f /opt/zimbra/data/ldap/mdb/db/data.mdb  ] ; then
   echo "postoje ldap podaci"
   exit 1
fi

#echo "/opt/zimbra/conf_0 - conf volume"
#rm -rf /opt/zimbra/conf/*

fix_zimbra_priviledges



#mv /opt/zimbra/conf_0/* /opt/zimbra/conf/

# NOTE: Currently genesis tests assume that the zmhostname == zimbra_default_domain
#       A fix for this is in progress
zimbra_fqdn=${ZIMBRA_HOST_NAME}
update_host_entry ${zimbra_fqdn}
update_tzdata_config

# update init/config (passwords)
update_zmsetup_config_file


# Configure Zimbra
/opt/zimbra/libexec/zmsetup.pl -c /init/config
echo "Enable admin access via proxy. Required for SOAP Harness tests "
sudo -i -u zimbra /opt/zimbra/libexec/zmproxyconfig -e -w -C -H ${ZIMBRA_HOST_NAME}
echo "Disable max imap/pop3 max error limits. Required for Genesis"
sudo -i -u zimbra zmlocalconfig -e imap_max_consecutive_error=0 pop3_max_consecutive_error=0
post_zmsetup_configuration 
#configure_staf 


/init/backup_config

#echo "SETUP COMPLETE"
#/bin/sleep infinity

