#!/bin/bash
source /init/init-common


if  [ -f /opt/zimbra/data/ldap/mdb/db/data.mdb  ] ; then
   echo "postoje ldap podaci"
   exit 1
fi

#echo "/opt/zimbra/conf_0 - conf volume"
#rm -rf /opt/zimbra/conf/*

fix_zimbra_priviledges



#mv /opt/zimbra/conf_0/* /opt/zimbra/conf/

# NOTE: Currently genesis tests assume that the zmhostname == zimbra_default_domain
#       A fix for this is in progress
zimbra_fqdn=${ZIMBRA_HOST_NAME}
update_host_entry ${zimbra_fqdn}
update_tzdata_config

# update init/config (passwords)
update_zmsetup_config_file


# Configure Zimbra
/opt/zimbra/libexec/zmsetup.pl -c /init/config
echo "Enable admin access via proxy. Required for SOAP Harness tests "
sudo -i -u zimbra /opt/zimbra/libexec/zmproxyconfig -e -w -C -H ${ZIMBRA_HOST_NAME}
echo "Disable max imap/pop3 max error limits. Required for Genesis"
sudo -i -u zimbra zmlocalconfig -e imap_max_consecutive_error=0 pop3_max_consecutive_error=0
post_zmsetup_configuration 
#configure_staf 

copy_etc_2_docker_etc
copy_zimbra_common_etc_conf_2_docker_etc

tar cfz /docker_etc/logger.tar.gz /opt/zimbra/logger/
tar cfz /docker_etc/zimbra_ssh.tar.gz /opt/zimbra/.ssh
tar cfz /docker_etc/zimbra_saveconfig.tar.gz /opt/zimbra/.saveconfig
tar cfz /docker_etc/spamassassin.tar.gz /opt/zimbra/data/spamassassin/
tar cfz /docker_etc/etc_ssh.tar.gz /etc/ssh

tar cfz /docker_etc/jetty_base.tar.gz /opt/zimbra/jetty_base/
tar cfz /docker_etc/cache_debconf.tar.gz /var/cache/debconf
#echo "SETUP COMPLETE"
#/bin/sleep infinity

