#!/bin/bash

# hernad 27.10.2018; v29

source /init/init-common

cp -av /docker_etc/etc/* /etc/

if [ ! -f /opt/zimbra/common/etc/java/cacerts ] ; then
   cp -av /docker_etc/common_etc/* /opt/zimbra/common/etc/
fi

if [ ! -f /opt/zimbra/conf/dhparam.pem ] ; then
   cp -av /docker_etc/conf/* /opt/zimbra/conf/
fi

if [ ! -f /opt/zimbra/common/conf/master.cf ] ; then
   cp -av /docker_etc/common_conf/* /opt/zimbra/common/conf/
fi

cd /
echo "extract instance configuration created during create instance phase:"
echo "   /opt/zimbra/jetty_base, logger, zimbra_ssh, spamassassin, cache_debconf tars"

if [ ! -f /opt/zimbra/logger/db/data/logger.sqlitedb ] ; then
  tar xf /docker_etc/logger.tar.gz
fi

if [ ! -f /opt/zimbra/.ssh/zimbra_identity ] ; then
  tar xf /docker_etc/zimbra_ssh.tar.gz
fi

if [ ! -f /opt/zimbra/.saveconfig/slapd.key ] ; then
  tar xf /docker_etc/zimbra_saveconfig.tar.gz
fi


if [ ! -f /opt/zimbra/data/spamassassin/localrules/salocal.cf ] ; then
   tar xf /docker_etc/spamassassin.tar.gz
fi

if [ ! -f /etc/ssh/ssh_host_rsa_key.pub ] ; then
    tar xf /docker_etc/etc_ssh.tar.gz
fi

tar xf /docker_etc/jetty_base.tar.gz
tar xf /docker_etc/cache_debconf.tar.gz

cp -av /init/rsyslog/logrotate_zimbra /etc/logrotate.d/zimbra
chmod 0644 /etc/logrotate.d/zimbra



fix_zimbra_priviledges

service ssh start
service ssh status

#echo "zmfixperms - ovo ce potrajati ..."
#/opt/zimbra/libexec/zmfixperms -e -v

chmod g+w /opt/zimbra/common/conf

su - zimbra -c "/opt/zimbra/bin/zmcontrol stop"
su - zimbra -c "/opt/zimbra/bin/zmcontrol start"


echo "zimbra version:"
su - zimbra -c "zmprov getServer ${ZIMBRA_HOST_NAME} zimbraServerVersion"

ZIMBRA_RESTART=0
ZIMLET=tk_barrydegraaff_account_history
if  !  su - zimbra -c "zmzimletctl info $ZIMLET" ; then
  su - zimbra -c "zmzimletctl deploy /opt/zimbra/zimlets/$ZIMLET.zip"
  ZIMBRA_RESTART=1
fi

ZIMLET=tk_barrydegraaff_accounthistory_admin
if  !  su - zimbra -c "zmzimletctl info $ZIMLET" ; then
  su - zimbra -c "zmzimletctl deploy /opt/zimbra/zimlets/$ZIMLET.zip"
  ZIMBRA_RESTART=1
fi

if [ "$ZIMBRA_RESTART" == "1" ] ; then
  su - zimbra -c "zmcontrol restart"
fi

if ! su - zimbra -c "zmstatctl status"  ; then
   su - zimbra -c "zmstatctl restart"
fi


# https://github.com/Zimbra-Community/account-history#log-external-ip
su - zimbra -c "zmlocalconfig zimbra_http_originating_ip_header"
su - zimbra -c "zmlocalconfig -c zimbra_http_originating_ip_header=X-Forwarded-For"
su - zimbra -c "zmprov mcf +zimbraMailTrustedIP 127.0.0.1"

su - zimbra -c "zmprov ms $ZIMBRA_SERVER zimbraMtaMyNetworks '$ZIMBRA_MY_NETWORKS'"
su - zimbra -c "zmprov ms $ZIMBRA_SERVER zimbraMtaRelayHost $ZIMBRA_GATEWAY"


echo "forwarding iskljucen - antispam/antiforge mjera"
su - zimbra -c "zmprov modifyCos defaultExternal zimbraFeatureMailForwardingEnabled FALSE"
su - zimbra -c "zmprov modifyCos default zimbraFeatureMailForwardingEnabled FALSE"

echo "disable chat service"
su - zimbra -c "zmprov ms $ZIMBRA_SERVER zimbraChatServiceEnabled FALSE"

su - zimbra -c "zmzimletctl disable com_zextras_chat_open"
su - zimbra -c "zmzimletctl undeploy com_zextras_chat_open"


#su - zimbra -c "zmtlsctl both"

su - zimbra -c "/init/antispam_setup"

# nakon setupa zimbraMtaMyNetworks, zimbraMtaRelayHost restart postfix
su - zimbra -c "zmcontrol restart"

restart_cron_rsyslogd

echo sacekajmo 7sec ... 
sleep 7
if [ ! -s /var/log/zimbra-stats.log  ] ; then
   echo "/var/log/zimbra-stats.log treba ponoviti start rsyslogd servisa"
   restart_cron_rsyslogd
   su - zimbra -c "zmcontrol restart"
fi

echo "===RUN_END=="
tail -f /dev/null