FROM ubuntu:16.04


ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y \
    curl \
    iputils-ping \
    dnsutils \
    gettext \
    linux-tools-common \
    openssh-server \
    netbase \
    netcat \
    net-tools \
    openjdk-8-jdk \
    rsyslog \
    software-properties-common \
    vim \
    wget && \
    apt-get install -y man psutils psmisc gcc && \
    apt-get install -y tzdata && \
    apt-get clean

# echo "tzdata tzdata/Areas select Etc" > /tmp/tzdata.txt && \
#    echo "tzdata tzdata/Zones/Etc select UTC" >> /tmp/tzdata.txt && \
#    export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true && \
#    debconf-set-selections /tmp/tzdata.txt && \


# ************************************************************************
# The following is required for Genesis tests to be run.
# NOTE: Work is in progress to allow for remote test execution
# 1. Disable setting that prevents users from writing to current terminal device 
# 2. Symlink in /bin/env (some genesis tests expect it to be there)
# 3. Pre-create the zimbra user with known uid/gid so that IF a user wants to mount a host
# 4. directory into the container, the permissions will be correct.
# ************************************************************************
RUN sed -i.bak 's/^mesg/# mesg/' /root/.profile && \
    ln -s /usr/bin/env /bin/env && \
    groupadd -r -g 1000 zimbra && \
    useradd -r -g zimbra -u 1000 -b /opt -s /bin/bash zimbra

# ************************************************************************
# Download and do a package-only install of Zimbra
# Trick build into skipping resolvconf as docker overrides for DNS
# This is currently required by our installer script. Hopefully be
# fixed soon.  The `zimbra-os-requirements` packages depends
# on the `resolvconf` package, and configuration of that is what
# was breaking install.sh
# ************************************************************************

ENV ZIMBRA_MAJOR 8.8.9_GA
ENV ZIMBRA_FILE_BASE zcs-8.8.9_GA_3019.UBUNTU16_64.20180809160254

ENV ZIMBRA_TGZ https://files.zimbra.com/downloads/$ZIMBRA_MAJOR/${ZIMBRA_FILE_BASE}.tgz
RUN curl -s -k -o /tmp/zcs.tgz $ZIMBRA_TGZ && \
    mkdir -p /tmp/release && \
    tar xzvf /tmp/zcs.tgz -C /tmp/release --strip-components=1 && \
    rm /tmp/zcs.tgz && \
    echo "resolvconf resolvconf/linkify-resolvconf boolean false" | debconf-set-selections

COPY slash-zimbra/software-install-responses /tmp/software-install-responses
WORKDIR /tmp/release
RUN sed -i.bak 's/checkRequired/# checkRequired/' install.sh && \
    ./install.sh -s -x --skip-upgrade-check < /tmp/software-install-responses && \
    apt-get clean && \
    rm -rf /tmp/release

RUN apt-get -y install zimbra-chat zimbra-drive

EXPOSE 22 25 80 110 143 443 465 587 993 995 7071 8443
