#!/bin/bash

source zimbra_common.sh

docker rm -f $NAME

docker run -ti \
      --name $NAME \
      -p 7071:7071  \
      -p 8143:143   \
      -p 9443:443   \
      -p 8993:993   \
      \
      -v $VOL_ZIMBRA_INIT:$VOL_ZIMBRA_INIT_SESSION \
      -v $VOL_ZIMBRA_ETC:$VOL_ZIMBRA_ETC_SESSION \
      \
      -v $VOL_ZIMBRA_DB:$VOL_ZIMBRA_DB_SESSION \
      -v $VOL_ZIMBRA_POSTFIX:$VOL_ZIMBRA_POSTFIX_SESSION \
      -v $VOL_ZIMBRA_POSTFIX_2:$VOL_ZIMBRA_POSTFIX_2_SESSION \
      -v $VOL_ZIMBRA_STORE:$VOL_ZIMBRA_STORE_SESSION \
      \
      -v $VOL_ZIMBRA_LOG:$VOL_ZIMBRA_LOG_SESSION \
      -v $VOL_ZIMBRA_CONF:$VOL_ZIMBRA_CONF_SESSION \
      \
      -v $VOL_ZIMBRA_LDAP:$VOL_ZIMBRA_LDAP_SESSION \
      -v $VOL_ZIMBRA_LDAP_2:$VOL_ZIMBRA_LDAP_2_SESSION \
      -v $VOL_ZIMBRA_LDAP_3:$VOL_ZIMBRA_LDAP_3_SESSION \
      \
      -v $VOL_ZIMBRA_LOGGER:$VOL_ZIMBRA_LOGGER_SESSION \
      -v $VOL_ZIMBRA_SSL:$VOL_ZIMBRA_SSL_SESSION \
      -v $VOL_ZIMBRA_CLAMAV:$VOL_ZIMBRA_CLAMAV_SESSION \
      -v $VOL_ZIMBRA_AMAVISD:$VOL_ZIMBRA_AMAVISD_SESSION \
      -v $VOL_ZIMBRA_AMAVISD:$VOL_ZIMBRA_ZIMLETS \
       \
       $IMG bash


