#!/bin/bash

source zimbra_common.sh

if [ -d zimbra/cmmmon ] ; then
  echo "direktorij zimbra/cmmmon preimenovati u zimbra/common"
  exit 1
fi

docker rm -f $ZIMBRA_INSTANCE_NAME

echo volume $VOL_ZIMBRA_CONF:$VOL_ZIMBRA_CONF_SESSION  only when running instance
echo '+ volume common/conf, common/etc, logger, /etc/ssh'
echo "+ gw: $ZIMBRA_GATEWAY, my_networks: $ZIMBRA_MY_NETWORKS"
docker run  -d \
      -h $ZIMBRA_HOST_NAME \
      --name $ZIMBRA_INSTANCE_NAME \
      --restart unless-stopped \
      -e ZIMBRA_DEFAULT_DOMAIN=$ZIMBRA_DEFAULT_DOMAIN \
      -e ZIMBRA_HOST_NAME=$ZIMBRA_HOST_NAME \
      -p 7071:7071  \
      -p 8443:8443 \
      -p 8143:143  \
      -p 993:$ZIMBRA_IMAPS_PORT \
      -p 8088:80   \
      -p 8025:25   \
      -p 587:587   \
      -p 465:465   \
      \
      -e ZIMBRA_SERVER=$ZIMBRA_HOST_NAME \
      -e ZIMBRA_GATEWAY=$ZIMBRA_GATEWAY \
      -e ZIMBRA_MY_NETWORKS="$ZIMBRA_MY_NETWORKS" \
      \
      -v $VOL_ZIMBRA_INIT:$VOL_ZIMBRA_INIT_SESSION \
      -v $VOL_ZIMBRA_ETC:$VOL_ZIMBRA_ETC_SESSION \
      \
      -v $VOL_ZIMBRA_DB:$VOL_ZIMBRA_DB_SESSION \
      -v $VOL_ZIMBRA_POSTFIX:$VOL_ZIMBRA_POSTFIX_SESSION \
      -v $VOL_ZIMBRA_POSTFIX_2:$VOL_ZIMBRA_POSTFIX_2_SESSION \
      -v $VOL_ZIMBRA_STORE:$VOL_ZIMBRA_STORE_SESSION \
      \
      -v $VOL_ZIMBRA_LOG:$VOL_ZIMBRA_LOG_SESSION \
      -v $VOL_ZIMBRA_LOG_2:$VOL_ZIMBRA_LOG_2_SESSION \
      -v $VOL_ZIMBRA_INDEX:$VOL_ZIMBRA_INDEX_SESSION \
      \
      -v $VOL_ZIMBRA_LDAP:$VOL_ZIMBRA_LDAP_SESSION \
      -v $VOL_ZIMBRA_LDAP_2:$VOL_ZIMBRA_LDAP_2_SESSION \
      -v $VOL_ZIMBRA_LDAP_3:$VOL_ZIMBRA_LDAP_3_SESSION \
      \
      -v $VOL_ZIMBRA_LOGGER:$VOL_ZIMBRA_LOGGER_SESSION \
      -v $VOL_ZIMBRA_SSL:$VOL_ZIMBRA_SSL_SESSION \
      -v $VOL_ZIMBRA_CLAMAV:$VOL_ZIMBRA_CLAMAV_SESSION \
      -v $VOL_ZIMBRA_AMAVISD:$VOL_ZIMBRA_AMAVISD_SESSION \
      \
      -v $VOL_ZIMBRA_ZIMLETS:$VOL_ZIMBRA_ZIMLETS_SESSION \
      -v $VOL_ZIMBRA_TMP:$VOL_ZIMBRA_TMP_SESSION \
       \
      -v $VOL_ZIMBRA_POSTFIX_2:$VOL_ZIMBRA_POSTFIX_2_SESSION \
      -v $VOL_ZIMBRA_POSTFIX:$VOL_ZIMBRA_POSTFIX_SESSION \
      \
      -v $VOL_ZIMBRA_CONF:$VOL_ZIMBRA_CONF_SESSION \
      -v $VOL_ZIMBRA_COMMON:$VOL_ZIMBRA_COMMON_SESSION \
      -v $VOL_ZIMBRA_COMMON_2:$VOL_ZIMBRA_COMMON_2_SESSION \
      \
      -v $VOL_ZIMBRA_ZMSTAT:$VOL_ZIMBRA_ZMSTAT_SESSION \
      -v $VOL_ZIMBRA_CRONTABS:$VOL_ZIMBRA_CRONTABS_SESSION \
      -v $VOL_ZIMBRA_REDOLOG:$VOL_ZIMBRA_REDOLOG_SESSION \
      \
      -v $VOL_ZIMBRA_SSH:$VOL_ZIMBRA_SSH_SESSION \
      \
      -v $VOL_ZIMBRA_HOME_SSH:$VOL_ZIMBRA_HOME_SSH_SESSION \
      -v $VOL_ZIMBRA_HOME_SAVECONFIG:$VOL_ZIMBRA_HOME_SAVECONFIG_SESSION \
      \
      $ZIMBRA_IMG /init/run_instance
